[package]
name = "zos-backend"
version = "0.0.1"
edition = "2024"

[dependencies]
axum = { version = "0.8.7", features = ["ws"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
utoipa = { version = "5.4.0", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "9.0.2", features = ["axum"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# For DTrace/USDT
usdt = "0.6"

# For OpenTelemetry
tracing-opentelemetry = "0.32.0"
opentelemetry = { version = "0.31.0" }
opentelemetry_sdk = { version = "0.31.0", features = ["trace", "rt-tokio"] }
opentelemetry-otlp = { version = "0.31.0", features = ["trace", "grpc-tonic", "metrics"] }

# For PAM authentication
pam-sys = "1.0.0-alpha5"
libc = "0.2"

# For TLS
rcgen = "0.14.5"
axum-server = { version = "0.8.0", features = ["tls-rustls"] }

# For Session Management
tower-cookies = "0.11.0"
tower-sessions = { version = "0.14.0", features = ["memory-store", "private"] }
async-trait = "0.1"
tower-sessions-core = "0.14.0"
notify = "8.2.0"
rand = "0.8.5"
rand_core = "0.6.4"
time = "0.3"
axum_csrf = { version = "0.11.0", features = ["layer"] }

[dev-dependencies]
http-body-util = "0.1"
hyper = { version = "1", features = ["full"] }
tower = { version = "0.5.2", features = ["full"] }
tempfile = "3.23.0"
